if(EXISTS "/home/runner/work/treebot_interfaceboard_sw_linux/treebot_interfaceboard_sw_linux/t113i_daemon/build_ci/tests/integration_test_tcp_loopback[1]_tests.cmake")
  include("/home/runner/work/treebot_interfaceboard_sw_linux/treebot_interfaceboard_sw_linux/t113i_daemon/build_ci/tests/integration_test_tcp_loopback[1]_tests.cmake")
else()
  add_test(integration_test_tcp_loopback_NOT_BUILT integration_test_tcp_loopback_NOT_BUILT)
endif()
