if(EXISTS "/home/runner/work/treebot_interfaceboard_sw_linux/treebot_interfaceboard_sw_linux/t113i_daemon/build_ci/tests/test_utils[1]_tests.cmake")
  include("/home/runner/work/treebot_interfaceboard_sw_linux/treebot_interfaceboard_sw_linux/t113i_daemon/build_ci/tests/test_utils[1]_tests.cmake")
else()
  add_test(test_utils_NOT_BUILT test_utils_NOT_BUILT)
endif()
