if(EXISTS "/home/runner/work/treebot_interfaceboard_sw_linux/treebot_interfaceboard_sw_linux/t113i_daemon/build_ci/tests/test_task_manager[1]_tests.cmake")
  include("/home/runner/work/treebot_interfaceboard_sw_linux/treebot_interfaceboard_sw_linux/t113i_daemon/build_ci/tests/test_task_manager[1]_tests.cmake")
else()
  add_test(test_task_manager_NOT_BUILT test_task_manager_NOT_BUILT)
endif()
