if(EXISTS "/home/runner/work/treebot_interfaceboard_sw_linux/treebot_interfaceboard_sw_linux/t113i_daemon/build_ci/tests/test_module_initializer[1]_tests.cmake")
  include("/home/runner/work/treebot_interfaceboard_sw_linux/treebot_interfaceboard_sw_linux/t113i_daemon/build_ci/tests/test_module_initializer[1]_tests.cmake")
else()
  add_test(test_module_initializer_NOT_BUILT test_module_initializer_NOT_BUILT)
endif()
